module FFI::Chm::Const
  MAX_PATHLEN = 512

  UNCOMPRESSED = 0
  COMPRESSED = 1

  PARAM_MAX_BLOCKS_CACHED = 0

  RESOLVE_SUCCESS = 0
  RESOLVE_FAILURE = 1

  ENUMERATE_NORMAL = 1
  ENUMERATE_META = 2
  ENUMERATE_SPECIAL = 4

  ENUMERATE_FILES = 8
  ENUMERATE_DIRS = 16

  ENUMERATE_ALL = 31

  ENUMERATE_FLAGS = Hash[
    :normal, ENUMERATE_NORMAL,
    :meta, ENUMERATE_META,
    :special, ENUMERATE_SPECIAL,
    :files, ENUMERATE_FILES,
    :dirs, ENUMERATE_DIRS,
    :all, ENUMERATE_ALL
  ]

  ENUMERATOR_FAILURE = 0
  ENUMERATOR_CONTINUE = 1
  ENUMERATOR_SUCCESS = 2
end
